### ISSUE TITLE
工具中的配置实例截图是哪个？hysteria不是应该用文件添加自定义服务器吗？你这个是在哪个地方添加？

### ISSUE THREAD

**Issue by 889098** [zrlhk/alpine-hysteria2#1]
工具中的配置实例截图是哪个？hysteria不是应该用文件添加自定义服务器吗？你这个是在哪个地方添加？

**Comment by zrlhk** [comment]
这个是梯子工具，v2rayN。客户端工具自己搜，很多

**Comment by 889098** [comment]
> 这个是梯子工具，v2rayN。客户端工具自己搜，很多

没有你这个界面啊，你添加什么协议的？
